In [1]:
import numpy as np

In [2]:
A = np.array ( [[2,-1,0] , [0,1,2]] ).T
A

array([[ 2,  0],
       [-1,  1],
       [ 0,  2]])

In [3]:
b = np.array ( [[1, 0 ,- 1 ]] ).T
b.shape

(3, 1)

In [4]:
C = np.matmul(A.T , A)
print(C)

[[ 5 -1]
 [-1  5]]


In [5]:
inv_mat = np.linalg.inv(C)
inv_mat

array([[0.20833333, 0.04166667],
       [0.04166667, 0.20833333]])

In [6]:
D = np.matmul(inv_mat , A.T) 
x = np.matmul(D, b)
print(x)

[[ 0.33333333]
 [-0.33333333]]
